# Generated by Django 2.1.1 on 2019-06-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='str_date',
            field=models.CharField(default='-', max_length=64),
        ),
    ]
